export const DISPLAY_ALERT = "SHOW_ALERT"
export const CLEAR_ALERT = "CLEAR_ALERT"

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN"
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS"
export const SETUP_USER_ERROR = "SETUP_USER_ERROR"

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"

export const LOGOUT_USER = "LOGOUT_USER"

export const CLEAR_VALUES = "CLEAR_VALUES"

export const CREATE_NOTE_BEGIN = "CREATE_NOTE_BEGIN"
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS"
export const CREATE_NOTE_ERROR = "CREATE_NOTE_ERROR"

export const GET_NOTE_BEGIN = "GET_NOTE_BEGIN"
export const GET_NOTE_SUCCESS = "GET_NOTE_SUCCESS"
export const GET_NOTE_ERROR = "GET_NOTE_ERROR"
